
package com.redhat.gss.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.12.SP1-redhat-1
 * 2015-02-05T11:23:51.725-08:00
 * Generated source version: 2.7.12.SP1-redhat-1
 */

@WebFault(name = "Exception", targetNamespace = "http://ws.gss.redhat.com/")
public class Exception_Exception extends java.lang.Exception {
    
    private com.redhat.gss.ws.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, com.redhat.gss.ws.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, com.redhat.gss.ws.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public com.redhat.gss.ws.Exception getFaultInfo() {
        return this.exception;
    }
}
