package com.redhat.gss.ws;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12.SP1-redhat-1
 * 2015-02-05T11:23:51.749-08:00
 * Generated source version: 2.7.12.SP1-redhat-1
 * 
 */
@WebService(targetNamespace = "http://ws.gss.redhat.com/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld {

    @RequestWrapper(localName = "sayHello", targetNamespace = "http://ws.gss.redhat.com/", className = "com.redhat.gss.ws.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://ws.gss.redhat.com/", className = "com.redhat.gss.ws.SayHelloResponse")
    @WebMethod(operationName = "sayHello")
    public Response<com.redhat.gss.ws.SayHelloResponse> sayHelloAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<java.lang.String> arg0
    );

    @RequestWrapper(localName = "sayHello", targetNamespace = "http://ws.gss.redhat.com/", className = "com.redhat.gss.ws.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://ws.gss.redhat.com/", className = "com.redhat.gss.ws.SayHelloResponse")
    @WebMethod(operationName = "sayHello")
    public Future<?> sayHelloAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<java.lang.String> arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<com.redhat.gss.ws.SayHelloResponse> asyncHandler
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://ws.gss.redhat.com/", className = "com.redhat.gss.ws.SayHello")
    @WebMethod
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://ws.gss.redhat.com/", className = "com.redhat.gss.ws.SayHelloResponse")
    public java.util.List<java.lang.String> sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<java.lang.String> arg0
    ) throws Exception_Exception;
}
